version: '3.8'

services:
  scanitknowit:
    build: .
    ports:
      - "3001:3001"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
    volumes:
      - ./server:/app/server
    restart: unless-stopped